filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/volcanoes_data.csv

output.logstash:
  hosts: ["server3:9704"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

